/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CRUD_Admin;
import static Control.Costume_CRUD.database;
import Control.Database;
import Model.Karyawan;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SELLA
 */
final public class Hapus_Admin extends javax.swing.JFrame {
    private Database database = new Database(); // Objek Database
    private CRUD_Admin crudAdmin; 
    /**
     * Creates new form Hapus_Admin
     */
    public Hapus_Admin() {
        initComponents();
        crudAdmin = new CRUD_Admin(database);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ID_Admin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table10 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        cari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_AdminActionPerformed(evt);
            }
        });
        jPanel1.add(ID_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 320, 60));

        table10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(table10);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 620, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SELLA\\Downloads\\1aaaaa.jpeg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 600));

        Kembali.setText("jButton2");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 503, 170, 60));

        Hapus.setText("jButton1");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 140, 50));

        cari.setText("jButton1");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        new Menu_Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void ID_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_AdminActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        String idKaryawan = ID_Admin.getText();
        if (!idKaryawan.isEmpty()) {
            crudAdmin.HapusKaryawan(idKaryawan);
            DefaultTableModel model = new DefaultTableModel();
            table10.setModel(model);
            ID_Admin.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Silakan masukkan ID Karyawan terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        String idKaryawan = ID_Admin.getText();
        if (!idKaryawan.isEmpty()){
            Karyawan karyawan = crudAdmin.getKaryawanByID(idKaryawan);
            if (karyawan != null) {
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("ID Karyawan");
                model.addColumn("Nama Karyawan");
                model.addColumn("Devisi");
                model.addColumn("Nomor Telepon");
                model.addColumn("Alamat");
                model.addColumn("Karyawan ID");

                Object[] row = {
                        karyawan.getID_Kar(),
                        karyawan.getNama_Karyawan(),
                        karyawan.getDevisi(),
                        karyawan.getNomor_Tlpn(),
                        karyawan.getAlamat(),
                        karyawan.getID_Kar_kep()};
                model.addRow(row);
                table10.setModel(model);
            } else {
                JOptionPane.showMessageDialog(null, "Data dengan ID Karyawan " + idKaryawan + " tidak ditemukan.", "Notifikasi", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silakan masukkan ID Karyawan terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hapus_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hapus_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hapus_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hapus_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hapus_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField ID_Admin;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table10;
    // End of variables declaration//GEN-END:variables
}
