/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
//import Control.LoginClass;
import Control.Database;
import View.Login;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Scanner;
import java.util.Iterator;
import Control.LoginClass;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
        
        

/**
 *
 * @author SELLA
 */


public class Login extends javax.swing.JFrame {
//    private Connection connection;
//    private String username; // Variable untuk menyimpan username
//    private String password;

    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
//        Username = new javax.swing.JTextField();
//        Password = new javax.swing.JPasswordField();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usernametxt = new javax.swing.JTextField();
        Passwordtxt = new javax.swing.JPasswordField();
        IconLogin = new javax.swing.JLabel();
        masuk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FrameLogin"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usernametxt.setBackground(new java.awt.Color(204, 204, 204));
        Usernametxt.setToolTipText("Username");
        Usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernametxtActionPerformed(evt);
            }
        });
        getContentPane().add(Usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 270, 30));

        Passwordtxt.setBackground(new java.awt.Color(204, 204, 204));
        Passwordtxt.setToolTipText("Password");
        Passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordtxtActionPerformed(evt);
            }
        });
        getContentPane().add(Passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 270, 30));

        IconLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\SELLA\\Downloads\\A1.jpeg")); // NOI18N
        getContentPane().add(IconLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 380));

        masuk.setText("Masuk");
        masuk.setToolTipText("");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        getContentPane().add(masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 273, 130, 40));

        setSize(new java.awt.Dimension(1054, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordtxtActionPerformed

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM pelayanan where username ='" + Usernametxt.getText() + "'AND password ='" + Passwordtxt.getText()+"'";
            java.sql.Connection conn = (Connection) Database.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                if (Usernametxt.getText().equals(rs.getString("username"))
                        && Passwordtxt.getText().equals(rs.getString("password"))) {
                        JOptionPane.showMessageDialog(null, "Login berhasil");
                        this.setVisible(false);
                        new Pilih_Menu().setVisible(true);
                        this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login gagal");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_masukActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentResized

    private void UsernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernametxtActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconLogin;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JButton masuk;
    // End of variables declaration//GEN-END:variables
}
