/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.Costume_CRUD;
import Control.Database;
import Model.Costume;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SELLA
 */
final public class Tambah_Anime extends javax.swing.JFrame {

    /**
     * Creates new form TambahAnime
     */
    public Tambah_Anime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Gender = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        ID_Costume = new javax.swing.JTextField();
        Nama_Karakter = new javax.swing.JTextField();
        Ukuran = new javax.swing.JTextField();
        Jenis_Costume = new javax.swing.JTextField();
        Pelayanan_ID = new javax.swing.JTextField();
        Pemasok_ID = new javax.swing.JTextField();
        IconAnime = new javax.swing.JLabel();
        KembaliAnime = new javax.swing.JButton();
        Tambahkan = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 396, 1131, -1));

        Gender.setToolTipText("Harga");
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, 40));

        Harga.setToolTipText("Ukuran");
        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        getContentPane().add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 130, 40));

        ID_Costume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_CostumeActionPerformed(evt);
            }
        });
        getContentPane().add(ID_Costume, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 40));

        Nama_Karakter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_KarakterActionPerformed(evt);
            }
        });
        getContentPane().add(Nama_Karakter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 190, 40));

        Ukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkuranActionPerformed(evt);
            }
        });
        getContentPane().add(Ukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 130, 40));

        Jenis_Costume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jenis_CostumeActionPerformed(evt);
            }
        });
        getContentPane().add(Jenis_Costume, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 120, 40));

        Pelayanan_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelayanan_IDActionPerformed(evt);
            }
        });
        getContentPane().add(Pelayanan_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 130, 40));

        Pemasok_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pemasok_IDActionPerformed(evt);
            }
        });
        getContentPane().add(Pemasok_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 130, 40));

        IconAnime.setIcon(new javax.swing.ImageIcon("C:\\Users\\SELLA\\Downloads\\11.jpeg")); // NOI18N
        getContentPane().add(IconAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 370));

        KembaliAnime.setText("jButton1");
        KembaliAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliAnimeActionPerformed(evt);
            }
        });
        getContentPane().add(KembaliAnime, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 303, 120, 50));

        Tambahkan.setText("jButton1");
        Tambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahkanActionPerformed(evt);
            }
        });
        getContentPane().add(Tambahkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_GenderActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HargaActionPerformed
    
    private void KembaliAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliAnimeActionPerformed
        // TODO add your handling code here:
          new Pilih_Menu().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_KembaliAnimeActionPerformed

    private void ID_CostumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_CostumeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ID_CostumeActionPerformed

    private void Nama_KarakterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_KarakterActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_Nama_KarakterActionPerformed

    private void TambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahkanActionPerformed
    String ID_Cos = ID_Costume.getText();
    String namaKarakter = Nama_Karakter.getText();
    String gender = Gender.getText();
    String hargaStr = Harga.getText(); // Mengambil harga sebagai string dari input
    String ukuran = Ukuran.getText();
    String Jenis = Jenis_Costume.getText();
    String idpelayan = Pelayanan_ID.getText();
    String idpemasok1 = Pemasok_ID.getText();
    
    try {
        if (ID_Cos.isEmpty() || namaKarakter.isEmpty() || gender.isEmpty() || hargaStr.isEmpty() || ukuran.isEmpty() || Jenis.isEmpty() || idpelayan.isEmpty() || idpemasok1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap lengkapi semua kolom input.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
    int harga = Integer.valueOf(hargaStr);
    Costume costume1 = new Costume(ID_Cos, namaKarakter, gender, harga, ukuran, Jenis, idpelayan, idpemasok1);

    String idCostume = Costume_CRUD.addCostumeKarakter(costume1);
    System.out.println(costume1.toString());

    if (idCostume == null) {
        JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan ke database.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        new Tambah_Anime2().setVisible(true);
        dispose();
    } 
    }catch (NumberFormatException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Gagal menambahkan data ke database. Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_TambahkanActionPerformed

    private void Pelayanan_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelayanan_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelayanan_IDActionPerformed

    private void UkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UkuranActionPerformed

    private void Jenis_CostumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jenis_CostumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jenis_CostumeActionPerformed

    private void Pemasok_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pemasok_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pemasok_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah_Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah_Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah_Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah_Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah_Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah_Anime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField ID_Costume;
    private javax.swing.JLabel IconAnime;
    private javax.swing.JTextField Jenis_Costume;
    private javax.swing.JButton KembaliAnime;
    private javax.swing.JTextField Nama_Karakter;
    private javax.swing.JTextField Pelayanan_ID;
    private javax.swing.JTextField Pemasok_ID;
    private javax.swing.JButton Tambahkan;
    private javax.swing.JTextField Ukuran;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
