/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Costume;
import Control.Costume_CRUD;
import javax.swing.JOptionPane;

/**
 *
 * @author SELLA
 */
final public class Tambah_Game extends javax.swing.JFrame {

    /**
     * Creates new form Tambah_Game
     */
    public Tambah_Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id_costume = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        namaKarakter = new javax.swing.JTextField();
        ukuran = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        pelayanan = new javax.swing.JTextField();
        pemasok = new javax.swing.JTextField();
        IconGame = new javax.swing.JLabel();
        KembaliGame = new javax.swing.JButton();
        LanjutGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_costume.setToolTipText("ID Costume");
        id_costume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_costumeActionPerformed(evt);
            }
        });
        jPanel1.add(id_costume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 40));

        gender.setToolTipText("Nama Karakter");
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 90, 40));

        harga.setToolTipText("Gender");
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 120, 40));

        namaKarakter.setToolTipText("Harga");
        namaKarakter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKarakterActionPerformed(evt);
            }
        });
        jPanel1.add(namaKarakter, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 40));

        ukuran.setToolTipText("Ukuran");
        ukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukuranActionPerformed(evt);
            }
        });
        jPanel1.add(ukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 100, 40));

        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 150, 40));

        pelayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayananActionPerformed(evt);
            }
        });
        jPanel1.add(pelayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 40));

        pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokActionPerformed(evt);
            }
        });
        jPanel1.add(pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 120, 40));

        IconGame.setIcon(new javax.swing.ImageIcon("C:\\Users\\SELLA\\Downloads\\13.jpeg")); // NOI18N
        jPanel1.add(IconGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        KembaliGame.setText("jButton2");
        KembaliGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliGameActionPerformed(evt);
            }
        });
        jPanel1.add(KembaliGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 303, 130, 40));

        LanjutGame.setText("jButton1");
        LanjutGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanjutGameActionPerformed(evt);
            }
        });
        jPanel1.add(LanjutGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ukuranActionPerformed

    private void id_costumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_costumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_costumeActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void namaKarakterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKarakterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKarakterActionPerformed

    private void LanjutGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanjutGameActionPerformed
        // TODO add your handling code here:
    String ID_Cos = id_costume.getText();
    String namaKarakter1 = namaKarakter.getText();
    String gender1 = gender.getText();
    String hargaStr = harga.getText(); // Mengambil harga sebagai string dari input
    String ukuran1 = ukuran.getText();
    String Jenis = jenis.getText();
    String idpelayan = pelayanan.getText();
    String idpemasok1 = pemasok.getText();
    
    try {
        if (ID_Cos.isEmpty() || namaKarakter1.isEmpty() || gender1.isEmpty() || hargaStr.isEmpty() || ukuran1.isEmpty() || Jenis.isEmpty() || idpelayan.isEmpty() || idpemasok1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap lengkapi semua kolom input.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
    int harga = Integer.valueOf(hargaStr);
    Costume costume1 = new Costume(ID_Cos, namaKarakter1, gender1, harga, ukuran1, Jenis, idpelayan, idpemasok1);

    String idCostume = Costume_CRUD.addCostumeKarakter(costume1);
    System.out.println(costume1.toString());
 
    if (idCostume == null) {
        JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan ke database.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        new Tambah_Game2().setVisible(true);
        dispose();
    } 
    }catch (NumberFormatException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Gagal menambahkan data ke database. Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    
    }//GEN-LAST:event_LanjutGameActionPerformed

    private void KembaliGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliGameActionPerformed
        // TODO add your handling code here:
        new Menu_Awal().setVisible(true);
        dispose();
    }//GEN-LAST:event_KembaliGameActionPerformed

    private void pelayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelayananActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemasokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconGame;
    private javax.swing.JButton KembaliGame;
    private javax.swing.JButton LanjutGame;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_costume;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField namaKarakter;
    private javax.swing.JTextField pelayanan;
    private javax.swing.JTextField pemasok;
    private javax.swing.JTextField ukuran;
    // End of variables declaration//GEN-END:variables
}
