/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.Costume_CRUD;
import Model.Karyawan;
import javax.swing.JOptionPane;
import Control.CRUD_Admin;
import Control.Database;
import static Control.Database.configDB;

/**
 *
 * @author SELLA
 */
final public class Tambah_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Tambah_Admin
     */
    public Tambah_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTAdmin = new javax.swing.JPanel();
        ID_Admin = new javax.swing.JTextField();
        Nama_karyawan = new javax.swing.JTextField();
        no_tlpn = new javax.swing.JTextField();
        Devisi = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        Lanjut = new javax.swing.JButton();
        id_kep = new javax.swing.JTextField();
        Icon_TambahKaryawan = new javax.swing.JLabel();
        Button_Tambahkan = new javax.swing.JButton();
        kembali2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FrameTAdmin"); // NOI18N

        PanelTAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID_Admin.setToolTipText("ID_Admin");
        ID_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_AdminActionPerformed(evt);
            }
        });
        PanelTAdmin.add(ID_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 350, 40));

        Nama_karyawan.setToolTipText("Username");
        Nama_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_karyawanActionPerformed(evt);
            }
        });
        PanelTAdmin.add(Nama_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 350, 40));

        no_tlpn.setToolTipText("Nama Lengkap");
        no_tlpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_tlpnActionPerformed(evt);
            }
        });
        PanelTAdmin.add(no_tlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 350, 40));

        Devisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevisiActionPerformed(evt);
            }
        });
        PanelTAdmin.add(Devisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 350, 40));

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        PanelTAdmin.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 170, 40));

        Lanjut.setText("Lanjut");
        Lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanjutActionPerformed(evt);
            }
        });
        PanelTAdmin.add(Lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 170, 30));

        id_kep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_kepActionPerformed(evt);
            }
        });
        PanelTAdmin.add(id_kep, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 150, 40));

        Icon_TambahKaryawan.setIcon(new javax.swing.ImageIcon("C:\\Users\\SELLA\\Downloads\\A25.jpeg")); // NOI18N
        PanelTAdmin.add(Icon_TambahKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));

        Button_Tambahkan.setText("jButton1");
        PanelTAdmin.add(Button_Tambahkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 433, 170, 30));

        kembali2.setText("jButton1");
        kembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali2ActionPerformed(evt);
            }
        });
        PanelTAdmin.add(kembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 503, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_AdminActionPerformed

    private void Nama_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_karyawanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Nama_karyawanActionPerformed

    private void kembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali2ActionPerformed
        // TODO add your handling code here:
        new Menu_Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembali2ActionPerformed

    private void LanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanjutActionPerformed
    // TODO add your handling code here:
    String ID_Kar = ID_Admin.getText();
    String Nama_Karyawan = Nama_karyawan.getText();
    String devisi = Devisi.getText();
    String Nomor_Tlpn = no_tlpn.getText();      
    String Alamat = alamat.getText();
    String ID_Kar_kep = id_kep.getText();

try {
    if (ID_Kar.isEmpty() || Nama_Karyawan.isEmpty() || devisi.isEmpty() || Nomor_Tlpn.isEmpty() || Alamat.isEmpty() || ID_Kar_kep.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Harap lengkapi semua kolom input.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double netlpn;
    try {
        netlpn = Double.parseDouble(Nomor_Tlpn);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Nomor Telepon harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Karyawan karyawan1 = new Karyawan(ID_Kar, Nama_Karyawan, devisi, (int) netlpn, Alamat, ID_Kar_kep);
        Database configDB = null;
    CRUD_Admin crudAdmin = new CRUD_Admin(configDB);
    crudAdmin.tambahKaryawan(karyawan1);

    JOptionPane.showMessageDialog(null, "Data karyawan berhasil ditambahkan ke database.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    new Tambah_Anime2().setVisible(true);
    dispose();
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Gagal menambahkan data ke database. Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_LanjutActionPerformed

    private void DevisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DevisiActionPerformed

    private void no_tlpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_tlpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_tlpnActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void id_kepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_kepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_kepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Tambahkan;
    private javax.swing.JTextField Devisi;
    private javax.swing.JTextField ID_Admin;
    private javax.swing.JLabel Icon_TambahKaryawan;
    private javax.swing.JButton Lanjut;
    private javax.swing.JTextField Nama_karyawan;
    private javax.swing.JPanel PanelTAdmin;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField id_kep;
    private javax.swing.JButton kembali2;
    private javax.swing.JTextField no_tlpn;
    // End of variables declaration//GEN-END:variables
}
